#pragma once
#include <gtkmm.h>
#include <vector>
#include "wrapbinary.hpp"
#include <filesystem>
#include <crow.h>
#include <crow/middlewares/session.h>

class config_view : public Gtk::Frame
{
private:
    /* data */
    const char *XML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
    "<interface>"
    "<requires lib=\"gtk\" version=\"4.0\"/>"
    "<object class=\"GtkBox\" id=\"box_configuracion\">"
        "<property name=\"orientation\">0</property>"
        "<child>"
        "<object class=\"GtkBox\">"
            "<property name=\"spacing\">5</property>"
            "<property name=\"orientation\">1</property>"
            "<child>"
            "<object class=\"GtkButton\" id=\"btn_back_config\">"
                "<property name=\"halign\">0</property>"
                "<property name=\"margin-start\">10</property>"
                "<property name=\"margin-end\">10</property>"
                "<property name=\"has-frame\">false</property>"
                "<property name=\"child\">"
                "<object class=\"GtkBox\">"
                    "<property name=\"spacing\">5</property>"
                    "<child>"
                    "<object class=\"GtkImage\">"
                        "<property name=\"icon-name\">go-previous-symbolic</property>"
                    "</object>"
                    "</child>"
                    "<child>"
                    "<object class=\"GtkLabel\">"
                        "<property name=\"label\">Regresar</property>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
            "<child>"
            "<object class=\"GtkSeparator\"></object>"
            "</child>"
            "<child>"
            "<object class=\"GtkStackSidebar\">"
                "<property name=\"stack\">stack_confi</property>"
                "<property name=\"vexpand\">true</property>"
            "</object>"
            "</child>"
        "</object>"
        "</child>"
        "<child>"
        "<object class=\"GtkStack\" id=\"stack_confi\">"
            "<property name=\"margin-bottom\">10</property>"
            "<property name=\"margin-start\">10</property>"
            "<property name=\"margin-end\">10</property>"
            "<property name=\"margin-top\">10</property>"
            "<property name=\"transition-type\">7</property>"
            "<child>"
            "<object class=\"GtkStackPage\">"
                "<property name=\"name\">page0</property>"
                "<property name=\"title\">General</property>"
                "<property name=\"icon-name\">display-symbolic</property>"
                "<property name=\"child\">"
                "<object class=\"GtkBox\">"
                    "<property name=\"orientation\">1</property>"
                    "<property name=\"spacing\">10</property>"
                    "<child>"
                    "<object class=\"GtkListBox\" id=\"list_configurable\">"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Mostrar Notificaciones</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkCheckButton\" id=\"check_config_notifi\">"
                                    "<property name=\"active\">true</property>"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"valign\">3</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Logo Inicio</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkButton\" id=\"btn_select_icon\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"child\">"
                                    "<object class=\"GtkBox\">"
                                        "<property name=\"spacing\">5</property>"
                                        "<child>"
                                        "<object class=\"GtkImage\">"
                                            "<property name=\"icon-name\">insert-image-symbolic</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkLabel\" id=\"lbl_path_icon\">"
                                            "<property name=\"label\">Selecciona Imagen</property>"
                                            "<property name=\"ellipsize\">1</property>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Mensaje de Inicio</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEntry\" id=\"ety_mensaje_inicio\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"valign\">3</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Carrusel de imágenes</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkButton\" id=\"btn_select_carrousel\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"margin-end\">10</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"child\">"
                                    "<object class=\"GtkBox\">"
                                        "<property name=\"spacing\">5</property>"
                                        "<child>"
                                        "<object class=\"GtkImage\">"
                                            "<property name=\"icon-name\">inode-directory-symbolic</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkLabel\" id=\"lbl_path_carrousel\">"
                                            "<property name=\"label\">Selecciona Carpeta</property>"
                                            "<property name=\"ellipsize\">1</property>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkDropDown\" id=\"Drop_temporizador\"></object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                    "</object>"
                    "</child>"
                    "<child>"
                    "<object class=\"GtkListBox\" id=\"list_config_general\">"
                        "<property name=\"selection-mode\">0</property>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Establecer PIN de acceso</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkImage\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"icon-name\">input-dialpad-symbolic</property>"
                                    "<property name=\"margin-end\">10</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Reiniciar</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkImage\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"icon-name\">system-reboot-symbolic</property>"
                                    "<property name=\"margin-end\">10</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Apagar</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkImage\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"icon-name\">system-shutdown-symbolic</property>"
                                    "<property name=\"margin-end\">10</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"label\">Restablecer de Fabrica</property>"
                                    "<property name=\"valign\">3</property>"
                                    "<property name=\"xalign\">0</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkImage\">"
                                    "<property name=\"halign\">2</property>"
                                    "<property name=\"icon-name\">computer-fail-symbolic</property>"
                                    "<property name=\"margin-end\">10</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                            "<style>"
                            "<class name=\"warning\"/>"
                            "<class name=\"activatable\"/>"
                            "</style>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
            "<child>"
            "<object class=\"GtkStackPage\">"
                "<property name=\"name\">page6</property>"
                "<property name=\"title\">Inf. del Sistema</property>"
                "<property name=\"icon-name\">display-symbolic</property>"
                "<property name=\"child\">"
                "<object class=\"GtkBox\">"
                    "<property name=\"orientation\">1</property>"
                    "<child>"
                    "<object class=\"GtkListBox\" id=\"list_info_systema\">"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"label\">Nombre del Dispositivo</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEditableLabel\" id=\"ety_info_host\">"
                                    "<property name=\"text\">Type here…</property>"
                                    "<property name=\"editable\">true</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"halign\">2</property>"
                                    "<style>"
                                    "<class name=\"dim-label\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\" id=\"entry_\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"label\">Modelo de Hardware</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEditableLabel\" id=\"ety_info_modelo\">"
                                    "<property name=\"text\">Type here…</property>"
                                    "<property name=\"editable\">false</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"halign\">2</property>"
                                    "<style>"
                                    "<class name=\"dim-label\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"label\">Procesador</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEditableLabel\" id=\"ety_info_procesador\">"
                                    "<property name=\"text\">Type here…</property>"
                                    "<property name=\"editable\">false</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"halign\">2</property>"
                                    "<style>"
                                    "<class name=\"dim-label\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"label\">Memoria</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEditableLabel\" id=\"ety_info_memoria\">"
                                    "<property name=\"text\">Type here…</property>"
                                    "<property name=\"editable\">false</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"halign\">2</property>"
                                    "<style>"
                                    "<class name=\"dim-label\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"halign\">1</property>"
                                    "<property name=\"label\">Disco</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEditableLabel\" id=\"ety_info_disco\">"
                                    "<property name=\"text\">Type here…</property>"
                                    "<property name=\"editable\">false</property>"
                                    "<property name=\"hexpand\">true</property>"
                                    "<property name=\"halign\">2</property>"
                                    "<style>"
                                    "<class name=\"dim-label\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
            "<child>"
            "<object class=\"GtkStackPage\">"
                "<property name=\"name\">page1</property>"
                "<property name=\"title\">Datos de Empresa</property>"
                "<property name=\"icon-name\">display-symbolic</property>"
                "<property name=\"child\">"
                "<object class=\"GtkBox\">"
                    "<property name=\"orientation\">1</property>"
                    "<child>"
                    "<object class=\"GtkListBox\" id=\"list_config_datos\">"
                        "<property name=\"selection-mode\">0</property>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\" id=\"entry_label_7\">"
                                    "<property name=\"xalign\">0</property>"
                                    "<property name=\"width-request\">110</property>"
                                    "<property name=\"label\">Razón social</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEntry\" id=\"ety_conf_razon\">"
                                    "<property name=\"placeholder-text\">Type here…</property>"
                                    "<property name=\"hexpand\">true</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\" id=\"entry_label_3\">"
                                    "<property name=\"xalign\">0</property>"
                                    "<property name=\"width-request\">110</property>"
                                    "<property name=\"label\">Direccion</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEntry\" id=\"ety_conf_direccion\">"
                                    "<property name=\"placeholder-text\">Type here…</property>"
                                    "<property name=\"hexpand\">true</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\" id=\"entry_label\">"
                                    "<property name=\"xalign\">0</property>"
                                    "<property name=\"width-request\">110</property>"
                                    "<property name=\"label\">RFC</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEntry\" id=\"ety_conf_rfc\">"
                                    "<property name=\"placeholder-text\">Type here…</property>"
                                    "<property name=\"hexpand\">true</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\" id=\"entry_label_4\">"
                                    "<property name=\"xalign\">0</property>"
                                    "<property name=\"width-request\">110</property>"
                                    "<property name=\"label\">Contacto</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEntry\" id=\"ety_conf_contacto\">"
                                    "<property name=\"placeholder-text\">Type here…</property>"
                                    "<property name=\"hexpand\">true</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                            "<property name=\"activatable\">false</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<child>"
                                "<object class=\"GtkLabel\" id=\"entry_label_5\">"
                                    "<property name=\"xalign\">0</property>"
                                    "<property name=\"width-request\">110</property>"
                                    "<property name=\"label\">Agradecimiento</property>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkEntry\" id=\"ety_conf_thanks\">"
                                    "<property name=\"placeholder-text\">Type here…</property>"
                                    "<property name=\"hexpand\">true</property>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
            "<child>"
            "<object class=\"GtkStackPage\">"
                "<property name=\"name\">page2</property>"
                "<property name=\"title\">Impresora</property>"
                "<property name=\"icon-name\">printer-symbolic</property>"
                "<property name=\"child\">"
                "<object class=\"GtkBox\">"
                    "<child>"
                    "<object class=\"GtkScrolledWindow\">"
                        "<property name=\"hexpand\">false</property>"
                        "<property name=\"hscrollbar-policy\">2</property>"
                        "<property name=\"vexpand\">true</property>"
                        "<child>"
                        "<object class=\"GtkViewport\">"
                            "<property name=\"scroll-to-focus\">true</property>"
                            "<child>"
                            "<object class=\"GtkBox\">"
                                "<property name=\"margin-bottom\">30</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"orientation\">1</property>"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"label\">Activar</property>"
                                    "<property name=\"margin-bottom\">10</property>"
                                    "<property name=\"xalign\">0</property>"
                                    "<style>"
                                    "<class name=\"title-2\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBox\" id=\"list_config\">"
                                    "<property name=\"selection-mode\">0</property>"
                                    "<property name=\"margin-bottom\">30</property>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"entry_label_activar\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Activar Impresión</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkSwitch\" id=\"switch_impresion\">"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<style>"
                                    "<class name=\"rich-list\"/>"
                                    "<class name=\"boxed-list\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"label\">Visualización</property>"
                                    "<property name=\"margin-bottom\">10</property>"
                                    "<property name=\"xalign\">0</property>"
                                    "<style>"
                                    "<class name=\"title-2\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBox\" id=\"list_config_visualizacion\">"
                                    "<property name=\"selection-mode\">0</property>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"switch_label\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Mensaje de Agradecimiento</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkCheckButton\" id=\"check_config_1\">"
                                                "<property name=\"active\">true</property>"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"margin-end\">10</property>"
                                                "<property name=\"margin-start\">10</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"check_label\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Fecha</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkCheckButton\" id=\"check_config_2\">"
                                                "<property name=\"active\">true</property>"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"margin-end\">10</property>"
                                                "<property name=\"margin-start\">10</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"check_label_2\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Direccion</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkCheckButton\" id=\"check_config_3\">"
                                                "<property name=\"active\">true</property>"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"margin-end\">10</property>"
                                                "<property name=\"margin-start\">10</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"check_label_3\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">RFC</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkCheckButton\" id=\"check_config_4\">"
                                                "<property name=\"active\">true</property>"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"margin-end\">10</property>"
                                                "<property name=\"margin-start\">10</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"check_label_4\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Vendedor</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkCheckButton\" id=\"check_config_5\">"
                                                "<property name=\"active\">true</property>"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"margin-end\">10</property>"
                                                "<property name=\"margin-start\">10</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"check_label_5\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Contacto</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkCheckButton\" id=\"check_config_6\">"
                                                "<property name=\"active\">true</property>"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"margin-end\">10</property>"
                                                "<property name=\"margin-start\">10</property>"
                                                "<property name=\"valign\">3</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<style>"
                                    "<class name=\"rich-list\"/>"
                                    "<class name=\"boxed-list\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkLabel\">"
                                    "<property name=\"label\">Test</property>"
                                    "<property name=\"margin-bottom\">10</property>"
                                    "<property name=\"margin-top\">30</property>"
                                    "<property name=\"xalign\">0</property>"
                                    "<style>"
                                    "<class name=\"title-2\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBox\" id=\"list_config_test\">"
                                    "<property name=\"selection-mode\">0</property>"
                                    "<child>"
                                    "<object class=\"GtkListBoxRow\">"
                                        "<child>"
                                        "<object class=\"GtkBox\">"
                                            "<child>"
                                            "<object class=\"GtkLabel\" id=\"entry_label_8\">"
                                                "<property name=\"halign\">1</property>"
                                                "<property name=\"hexpand\">true</property>"
                                                "<property name=\"label\">Impresion de Prueba</property>"
                                                "<property name=\"valign\">3</property>"
                                                "<property name=\"xalign\">0</property>"
                                            "</object>"
                                            "</child>"
                                            "<child>"
                                            "<object class=\"GtkImage\">"
                                                "<property name=\"halign\">2</property>"
                                                "<property name=\"icon-name\">printer-symbolic</property>"
                                            "</object>"
                                            "</child>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                    "<style>"
                                    "<class name=\"rich-list\"/>"
                                    "<class name=\"boxed-list\"/>"
                                    "</style>"
                                "</object>"
                                "</child>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                    "</object>"
                    "</child>"
                    "<child>"
                    "<object class=\"GtkScrolledWindow\">"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"margin-bottom\">20</property>"
                        "<property name=\"margin-end\">10</property>"
                        "<property name=\"margin-start\">30</property>"
                        "<property name=\"margin-top\">20</property>"
                        "<child>"
                        "<object class=\"GtkTextView\" id=\"text_ticket\">"
                            "<property name=\"cursor-visible\">false</property>"
                            "<property name=\"editable\">false</property>"
                            "<property name=\"input-purpose\">9</property>"
                            "<property name=\"left-margin\">5</property>"
                            "<property name=\"monospace\">true</property>"
                            "<property name=\"pixels-above-lines\">5</property>"
                            "<property name=\"pixels-below-lines\">5</property>"
                            "<property name=\"pixels-inside-wrap\">5</property>"
                            "<property name=\"right-margin\">5</property>"
                            "<property name=\"top-margin\">5</property>"
                            "<property name=\"wrap-mode\">3</property>"
                        "</object>"
                        "</child>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
            "<child>"
            "<object class=\"GtkStackPage\">"
                "<property name=\"name\">page3</property>"
                "<property name=\"title\">Usuarios</property>"
                "<property name=\"icon-name\">display-symbolic</property>"
                "<property name=\"child\">"
                "<object class=\"GtkBox\">"
                    "<property name=\"spacing\">10</property>"
                    "<child>"
                    "<object class=\"GtkScrolledWindow\">"
                        "<property name=\"vexpand\">true</property>"
                        "<property name=\"vexpand-set\">true</property>"
                        "<child>"
                        "<object class=\"GtkTreeView\" id=\"tree_venta\">"
                            "<property name=\"enable-grid-lines\">2</property>"
                            "<property name=\"enable-search\">false</property>"
                        "</object>"
                        "</child>"
                    "</object>"
                    "</child>"
                    "<child>"
                    "<object class=\"GtkFrame\">"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Permisos</property>"
                        "<child>"
                        "<object class=\"GtkGrid\">"
                            "<property name=\"column-homogeneous\">true</property>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_1\">"
                                "<property name=\"label\">Venta</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">0</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_2\">"
                                "<property name=\"label\">Pago</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">1</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_3\">"
                                "<property name=\"label\">Carga</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">2</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_4\">"
                                "<property name=\"label\">Retirada</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">3</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_5\">"
                                "<property name=\"label\">Cambio Manual</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">4</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_6\">"
                                "<property name=\"label\">Cambio Automatico</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">5</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_7\">"
                                "<property name=\"label\">Ingresos</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">6</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_8\">"
                                "<property name=\"label\">Enviar a casette</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">0</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_9\">"
                                "<property name=\"label\">Retirada Casette</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">1</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_10\">"
                                "<property name=\"label\">Consulta de Efectivo</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">2</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_11\">"
                                "<property name=\"label\">Mov. Pendientes</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">3</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_12\">"
                                "<property name=\"label\">Consulta Movimiento</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">4</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_13\">"
                                "<property name=\"label\">Cierre con Faltantes</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">5</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkSeparator\" id=\"check_rol_14\">"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">8</property>"
                                "<property name=\"column-span\">2</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_15\">"
                                "<property name=\"label\">Estadisticas</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">9</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_16\">"
                                "<property name=\"label\">Fianza</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">10</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_17\">"
                                "<property name=\"label\">Mostrar Reportes</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">0</property>"
                                "<property name=\"row\">11</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_18\">"
                                "<property name=\"label\">Configuracion</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">9</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_19\">"
                                "<property name=\"label\">Salir a Windows</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">10</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                            "<child>"
                            "<object class=\"GtkCheckButton\" id=\"check_rol_20\">"
                                "<property name=\"label\">Apagar el equipo</property>"
                                "<property name=\"halign\">1</property>"
                                "<property name=\"margin-end\">10</property>"
                                "<property name=\"margin-start\">10</property>"
                                "<property name=\"valign\">3</property>"
                                "<layout>"
                                "<property name=\"column\">1</property>"
                                "<property name=\"row\">11</property>"
                                "</layout>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
            "<child>"
            "<object class=\"GtkStackPage\">"
                "<property name=\"name\">page4</property>"
                "<property name=\"title\">Red</property>"
                "<property name=\"icon-name\">display-symbolic</property>"
                "<property name=\"child\">"
                "<object class=\"GtkScrolledWindow\">"
                    "<property name=\"hexpand\">false</property>"
                    "<property name=\"hscrollbar-policy\">2</property>"
                    "<property name=\"vexpand\">true</property>"
                    "<child>"
                    "<object class=\"GtkBox\">"
                        "<property name=\"orientation\">1</property>"
                        "<property name=\"spacing\">10</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                            "<property name=\"homogeneous\">true</property>"
                            "<child>"
                            "<object class=\"GtkListBox\" id=\"list_info_red\">"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Direccion IP WIFI</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_wifi\">"
                                            "<property name=\"text\">Type here…</property>"
                                            "<property name=\"editable\">false</property>"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                            "<style>"
                                            "<class name=\"dim-label\"/>"
                                            "</style>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Direccion Mac WIFI</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkEditableLabel\" id=\"ety_info_mac_wifi\">"
                                            "<property name=\"text\">Type here…</property>"
                                            "<property name=\"editable\">false</property>"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                            "<style>"
                                            "<class name=\"dim-label\"/>"
                                            "</style>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Direccion IP Ethernet</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_eth\">"
                                            "<property name=\"text\">Type here…</property>"
                                            "<property name=\"editable\">false</property>"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                            "<style>"
                                            "<class name=\"dim-label\"/>"
                                            "</style>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Direccion MAC Ethernet</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_eth_mac\">"
                                            "<property name=\"text\">Type here…</property>"
                                            "<property name=\"editable\">false</property>"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                            "<style>"
                                            "<class name=\"dim-label\"/>"
                                            "</style>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<style>"
                                "<class name=\"rich-list\"/>"
                                "<class name=\"boxed-list\"/>"
                                "</style>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                            "<property name=\"orientation\">1</property>"
                            "<child>"
                            "<object class=\"GtkListBox\" id=\"list_info_con\">"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Inálambrica</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkSwitch\" id=\"switch_active_wifi\">"
                                            "<property name=\"halign\">2</property>"
                                            "<property name=\"valign\">3</property>"
                                            "<property name=\"hexpand\">true</property>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">SSID</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkDropDown\" id=\"drop_list_ssdi\">"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Contraseña</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkPasswordEntry\" id=\"ety_pass_wifi\">"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                            "<property name=\"show-peek-icon\">true</property>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<child>"
                                "<object class=\"GtkListBoxRow\">"
                                    "<property name=\"activatable\">false</property>"
                                    "<child>"
                                    "<object class=\"GtkBox\">"
                                        "<child>"
                                        "<object class=\"GtkLabel\">"
                                            "<property name=\"halign\">1</property>"
                                            "<property name=\"label\">Test de conexión.</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkButton\" id=\"btn_probar_wifi\">"
                                            "<property name=\"label\">Probar</property>"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                        "</object>"
                                        "</child>"
                                        "<child>"
                                        "<object class=\"GtkButton\" id=\"btn_guardar_wifi\">"
                                            "<property name=\"label\">Guardar</property>"
                                            "<property name=\"hexpand\">true</property>"
                                            "<property name=\"halign\">2</property>"
                                            "<style>"
                                            "<class name=\"suggested-action\"/>"
                                            "</style>"
                                        "</object>"
                                        "</child>"
                                    "</object>"
                                    "</child>"
                                "</object>"
                                "</child>"
                                "<style>"
                                "<class name=\"rich-list\"/>"
                                "<class name=\"boxed-list\"/>"
                                "</style>"
                            "</object>"
                            "</child>"
                        "</object>"
                        "</child>"
                    "</object>"
                    "</child>"
                "</object>"
                "</property>"
            "</object>"
            "</child>"
        "</object>"
        "</child>"
    "</object>"
    "</interface>";
    //refrencias para volver al nodo principal
    Gtk::Box *&box_principal;
    Gtk::Stack &main_stack;
    Gtk::Window &main_window;
    Gtk::Label *&lbl_main;
    Gtk::Image *&img_main_logo;
    Gtk::Frame *&nip_set_view;

    Glib::RefPtr<Gtk::Builder> builder = Gtk::Builder::create();

    Gtk::Box *box_configuracion = nullptr;
    Gtk::Button *btn_back_config = nullptr;
    Gtk::Button *btn_select_carrousel = nullptr, *btn_select_icon = nullptr;
    Gtk::Label *lbl_path_icon = nullptr , *lbl_path_carrousel = nullptr;

    Gtk::Entry *ety_mensaje_inicio = nullptr;
    Gtk::DropDown *Drop_temporizador = nullptr;

    Gtk::ListBox *list_config_general = nullptr;
    Gtk::ListBox *list_config = nullptr;
    Gtk::ListBox *list_config_visualizacion = nullptr;
    Gtk::ListBox *list_config_test = nullptr;
    Gtk::ListBox *list_configurable = nullptr;

    Gtk::CheckButton *check_config_notifi = nullptr;

    Gtk::Switch *switch_impresion = nullptr;

    std::vector<Gtk::EditableLabel *> list_info_system = {nullptr,nullptr,nullptr,nullptr,nullptr};
    std::vector<Gtk::Entry *> list_ety_datos = {nullptr,nullptr,nullptr,nullptr,nullptr};
    std::vector<Gtk::CheckButton *> list_view_ticket = {nullptr,nullptr,nullptr,nullptr,nullptr,nullptr};

    std::unique_ptr<Gtk::MessageDialog> Dialog;
    //Gtk::CheckButton* chkb = Gtk::manage(new Gtk::CheckButton("Estoy consiente de la perdida completa de los datos del dispositivo."));

    //inicializaciones
    void init_info_systema();
    void inti_ety_datos();

    void init_signals_listas();
    void init_signals_config();
    void init_signals_impresion();


    //funciones internas
    std::string exec(const char* cmd);
    void on_button_file_clicked();
    void on_file_dialog_response(int response_id, Gtk::FileChooserDialog* dialog);
    void on_click_reboot();
    void on_click_shutdown();
    void on_rest_app();

public:
    config_view(Gtk::Box *&box_principal_, Gtk::Stack &main_stack_, Gtk::Window &main_window_, Gtk::Label *&lbl_main_, Gtk::Image *&img_main_logo_, Gtk::Frame *&nip_set_view_);
    ~config_view();
};