#pragma once
#include <gtkmm.h>
#include "wrapbinary.hpp"
#include "helper.hpp"

class view_one : public Gtk::Box
{
private:
    const char *PAGE0 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                        "<interface>"
                        "<object class=\"GtkBox\" id=\"page_0\">"
                        "<property name=\"orientation\">1</property>"
                        "<property name=\"spacing\">10</property>"
                        "<child>"
                        "<object class=\"GtkListBox\" id=\"list_configurable\">"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Mostrar Notificaciones</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkCheckButton\" id=\"check_config_notifi\">"
                        "<property name=\"active\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"valign\">3</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Logo Inicio</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkButton\" id=\"btn_select_icon\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"child\">"
                        "<object class=\"GtkBox\">"
                        "<property name=\"spacing\">5</property>"
                        "<child>"
                        "<object class=\"GtkImage\">"
                        "<property name=\"icon-name\">insert-image-symbolic</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkLabel\" id=\"lbl_path_icon\">"
                        "<property name=\"label\">Selecciona Imagen</property>"
                        "<property name=\"ellipsize\">1</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Mensaje de Inicio</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkEntry\" id=\"ety_mensaje_inicio\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"valign\">3</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Carrusel de imágenes</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkButton\" id=\"btn_select_carrousel\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"margin-end\">10</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"child\">"
                        "<object class=\"GtkBox\">"
                        "<property name=\"spacing\">5</property>"
                        "<child>"
                        "<object class=\"GtkImage\">"
                        "<property name=\"icon-name\">inode-directory-symbolic</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkLabel\" id=\"lbl_path_carrousel\">"
                        "<property name=\"label\">Selecciona Carpeta</property>"
                        "<property name=\"ellipsize\">1</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkDropDown\" id=\"Drop_temporizador\"></object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBox\" id=\"list_config_general\">"
                        "<property name=\"selection-mode\">0</property>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Establecer PIN de acceso</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkImage\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"icon-name\">input-dialpad-symbolic</property>"
                        "<property name=\"margin-end\">10</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Reiniciar</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkImage\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"icon-name\">system-reboot-symbolic</property>"
                        "<property name=\"margin-end\">10</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Apagar</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkImage\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"icon-name\">system-shutdown-symbolic</property>"
                        "<property name=\"margin-end\">10</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"label\">Restablecer de Fabrica</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"xalign\">0</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkImage\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"icon-name\">computer-fail-symbolic</property>"
                        "<property name=\"margin-end\">10</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"warning\"/>"
                        "<class name=\"activatable\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>";
    //===========================================================================
    Glib::RefPtr<Gtk::Builder> builder = Gtk::Builder::create();

    Gtk::Stack &main_stack;
    Gtk::Window &main_window;
    Gtk::Label *&lbl_main;
    Gtk::Image *&img_main_logo;
    Gtk::Frame *&nip_set_view;

    Gtk::Button *btn_select_carrousel = nullptr, *btn_select_icon = nullptr;
    Gtk::Label *lbl_path_icon = nullptr, *lbl_path_carrousel = nullptr;
    Gtk::CheckButton *check_config_notifi = nullptr;
    Gtk::Box *page_0 = nullptr;

    Gtk::ListBox *list_configurable = nullptr;
    Gtk::ListBox *list_config_general = nullptr;

    Gtk::Entry *ety_mensaje_inicio = nullptr;
    Gtk::DropDown *Drop_temporizador = nullptr;

    std::unique_ptr<Gtk::MessageDialog> Dialog;

    // funciones internas
    void init_signals_config();

    void on_button_file_clicked();
    void on_file_dialog_response(int response_id, Gtk::FileChooserDialog *dialog);
    void on_click_reboot();
    void on_click_shutdown();
    void on_rest_app();

public:
    view_one(Gtk::Stack &main_stack_, Gtk::Window &main_window_, Gtk::Label *&lbl_main_, Gtk::Image *&img_main_logo_, Gtk::Frame *&nip_set_view_);
    ~view_one();
};
