#pragma once
#include <gtkmm.h>
#include "niveles_almacenamiento.hpp"
#include "niveles_dinero.hpp"

class view_seven : public Gtk::Box
{
private:
    const char *PAGE7 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                        "<interface>\n"
                        "<requires lib=\"gtk\" version=\"4.0\"/>\n"
                        "<object class=\"GtkBox\" id=\"box_page_7\">\n"
                        "<property name=\"orientation\">1</property>\n"
                        "<property name=\"spacing\">10</property>\n"
                        "<property name=\"homogeneous\">false</property>\n"
                        "<property name=\"margin-bottom\">10</property>\n"
                        "<property name=\"margin-start\">10</property>\n"
                        "<property name=\"margin-end\">10</property>\n"
                        "<property name=\"margin-top\">10</property>\n"
                        "<child>\n"
                        "<object class=\"GtkFrame\">\n"
                        "<property name=\"label\">Billetes</property>\n"
                        "<child>\n"
                        "<object class=\"GtkGrid\">\n"
                        "<property name=\"vexpand\">false</property>\n"
                        "<property name=\"column-homogeneous\">false</property>\n"
                        "<property name=\"column-spacing\">38</property>\n"
                        "<property name=\"row-spacing\">2</property>\n"
                        "<property name=\"halign\">0</property>\n"
                        "<property name=\"margin-bottom\">10</property>\n"
                        "<property name=\"margin-start\">10</property>\n"
                        "<property name=\"margin-end\">10</property>\n"
                        "<property name=\"margin-top\">10</property>\n"
                        "<style>\n"
                        "<class name=\"title-2\"/>\n"
                        "</style>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">#</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">   Cantidad \nAlmacenada </property>\n"
                        "<layout>\n"
                        "<property name=\"column\">1</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">   Cantidad\nReciclador</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">2</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">         Nivel\nde Inmovilidad </property>\n"
                        "<layout>\n"
                        "<property name=\"column\">3</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$20</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$50</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$100</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$200</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$500</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$1000</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">6</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">Total</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">7</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-3\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_0\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_1\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">2</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_2\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_3\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_4\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_5\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">6</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_recy_6\">\n"
                        "<property name=\"label\">6</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">7</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-3\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_0\">\n"
                        "<property name=\"label\">1</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_1\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">1</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_2\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_3\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_4\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_5\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">6</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_bill_cant_6\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">7</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-3\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_bill_spin_0\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_bill_spin_1\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_bill_spin_2\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_bill_spin_3\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_bill_spin_4\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_bill_spin_5\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">6</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "</object>\n"
                        "</child>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkFrame\">\n"
                        "<property name=\"label\">Monedas</property>\n"
                        "<child>\n"
                        "<object class=\"GtkGrid\">\n"
                        "<property name=\"vexpand\">false</property>\n"
                        "<property name=\"column-homogeneous\">false</property>\n"
                        "<property name=\"column-spacing\">38</property>\n"
                        "<property name=\"row-spacing\">2</property>\n"
                        "<property name=\"halign\">0</property>\n"
                        "<property name=\"margin-bottom\">10</property>\n"
                        "<property name=\"margin-start\">10</property>\n"
                        "<property name=\"margin-end\">10</property>\n"
                        "<property name=\"margin-top\">10</property>\n"
                        "<style>\n"
                        "<class name=\"title-2\"/>\n"
                        "</style>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">#</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">   Cantidad \nAlmacenada </property>\n"
                        "<layout>\n"
                        "<property name=\"column\">1</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">   Cantidad\nReciclador</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">2</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">         Nivel\nde Inmovilidad </property>\n"
                        ""
                        "<layout>\n"
                        "<property name=\"column\">3</property>\n"
                        "<property name=\"row\">0</property>\n"
                        "</layout>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$1</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$2</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$5</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">$10</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\">\n"
                        "<property name=\"label\">Total</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">0</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-3\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_recy_0\">\n"
                        "<property name=\"label\">1</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_recy_1\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">2</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_recy_2\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_recy_3\">\n"
                        "<property name=\"label\">3</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_recy_4\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">02</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-3\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_cnt_0\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_cnt_1\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">1</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_cnt_2\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_cnt_3\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkLabel\" id=\"lbl_coin_cnt_4\">\n"
                        "<property name=\"label\">0</property>\n"
                        "<layout>\n"
                        "<property name=\"column\">01</property>\n"
                        "<property name=\"row\">5</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-3\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_coin_spin_0\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">1</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_coin_spin_1\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">2</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_coin_spin_2\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">3</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "<child>\n"
                        "<object class=\"GtkSpinButton\" id=\"lbl_coin_spin_3\">\n"
                        "<layout>\n"
                        "<property name=\"column\">03</property>\n"
                        "<property name=\"row\">4</property>\n"
                        "</layout>\n"
                        "<style>\n"
                        "<class name=\"title-4\"/>\n"
                        "</style>\n"
                        "</object>\n"
                        "</child>\n"
                        "</object>\n"
                        "</child>\n"
                        "</object>\n"
                        "</child>\n"
                        "</object>\n"
                        "</interface>\n";

    Glib::RefPtr<Gtk::Builder> builder = Gtk::Builder::create();
    Gtk::Box *box_page_7 = nullptr;
    Gtk::ScrolledWindow Wrap_box;    
    
    niveles_dinero nd;
    const int DENOMINACION_BILL[6] = {20,50,100,200,500,1000};
    const int DENOMINACION_COIN[4] = {1,2,5,10};
    
    // Funciones internas
    void init_widgets();

public:
    view_seven(/* args */);
    ~view_seven();
};