#pragma once
#include <gtkmm.h>

class view_six : public Gtk::Box
{
private:
    const char *PAGE5 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                        "<interface>"
                        "<object class=\"GtkBox\" id=\"page_5\">"
                        "<property name=\"orientation\">1</property>"
                        "<property name=\"spacing\">10</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<property name=\"homogeneous\">true</property>"
                        "<child>"
                        "<object class=\"GtkListBox\" id=\"list_info_red\">"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Direccion IP WIFI</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_wifi\">"
                        "<property name=\"text\">Type here…</property>"
                        "<property name=\"editable\">false</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<style>"
                        "<class name=\"dim-label\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Direccion Mac WIFI</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkEditableLabel\" id=\"ety_info_mac_wifi\">"
                        "<property name=\"text\">Type here…</property>"
                        "<property name=\"editable\">false</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<style>"
                        "<class name=\"dim-label\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Direccion IP Ethernet</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_eth\">"
                        "<property name=\"text\">Type here…</property>"
                        "<property name=\"editable\">false</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<style>"
                        "<class name=\"dim-label\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Direccion MAC Ethernet</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_eth_mac\">"
                        "<property name=\"text\">Type here…</property>"
                        "<property name=\"editable\">false</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<style>"
                        "<class name=\"dim-label\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<property name=\"orientation\">1</property>"
                        "<child>"
                        "<object class=\"GtkListBox\" id=\"list_info_con\">"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Inálambrica</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkSwitch\" id=\"switch_active_wifi\">"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"valign\">3</property>"
                        "<property name=\"hexpand\">true</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">SSID</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkDropDown\" id=\"drop_list_ssdi\">"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Contraseña</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkPasswordEntry\" id=\"ety_pass_wifi\">"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<property name=\"show-peek-icon\">true</property>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkListBoxRow\">"
                        "<property name=\"activatable\">false</property>"
                        "<child>"
                        "<object class=\"GtkBox\">"
                        "<child>"
                        "<object class=\"GtkLabel\">"
                        "<property name=\"halign\">1</property>"
                        "<property name=\"label\">Test de conexión.</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkButton\" id=\"btn_probar_wifi\">"
                        "<property name=\"label\">Probar</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "</object>"
                        "</child>"
                        "<child>"
                        "<object class=\"GtkButton\" id=\"btn_guardar_wifi\">"
                        "<property name=\"label\">Guardar</property>"
                        "<property name=\"hexpand\">true</property>"
                        "<property name=\"halign\">2</property>"
                        "<style>"
                        "<class name=\"suggested-action\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "<style>"
                        "<class name=\"rich-list\"/>"
                        "<class name=\"boxed-list\"/>"
                        "</style>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</child>"
                        "</object>"
                        "</interface>";
    Glib::RefPtr<Gtk::Builder> builder = Gtk::Builder::create();
    Gtk::Box *page_5 = nullptr;

    Gtk::EditableLabel *lbl_red[4] = {nullptr, nullptr, nullptr, nullptr};

    void init_datos_red();

public:
    view_six(/* args */);
    ~view_six();
};