#pragma once
#include <gtkmm.h>
#include "helper.hpp"

class view_six : public Gtk::Box
{
private:
  const char *PAGE5 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                      "<interface>"
                      "<requires lib=\"gtk\" version=\"4.0\"/>"
                      "<object class=\"GtkBox\" id=\"page_5\">"
                      "<property name=\"orientation\">1</property>"
                      "<property name=\"spacing\">10</property>"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"label\">Inalámbrica</property>"
                      "<property name=\"margin-bottom\">10</property>"
                      "<property name=\"xalign\">0</property>"
                      "<style>"
                      "<class name=\"title-2\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<property name=\"homogeneous\">true</property>"
                      "<child>"
                      "<object class=\"GtkListBox\" id=\"list_info_red\">"
                      "<child>"
                      "<object class=\"GtkListBoxRow\">"
                      "<property name=\"activatable\">false</property>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"halign\">1</property>"
                      "<property name=\"label\">SSID</property>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkEditableLabel\" id=\"ety_info_ssid_wifi\">"
                      "<property name=\"text\">Type here…</property>"
                      "<property name=\"editable\">false</property>"
                      "<property name=\"hexpand\">true</property>"
                      "<property name=\"halign\">2</property>"
                      "<style>"
                      "<class name=\"dim-label\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkListBoxRow\">"
                      "<property name=\"activatable\">false</property>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"halign\">1</property>"
                      "<property name=\"label\">Direccion IP</property>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_wifi\">"
                      "<property name=\"text\">Type here…</property>"
                      "<property name=\"editable\">false</property>"
                      "<property name=\"hexpand\">true</property>"
                      "<property name=\"halign\">2</property>"
                      "<style>"
                      "<class name=\"dim-label\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkListBoxRow\">"
                      "<property name=\"activatable\">false</property>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"halign\">1</property>"
                      "<property name=\"label\">Direccion Mac</property>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkEditableLabel\" id=\"ety_info_mac_wifi\">"
                      "<property name=\"text\">Type here…</property>"
                      "<property name=\"editable\">false</property>"
                      "<property name=\"hexpand\">true</property>"
                      "<property name=\"halign\">2</property>"
                      "<style>"
                      "<class name=\"dim-label\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "<style>"
                      "<class name=\"rich-list\"/>"
                      "<class name=\"boxed-list\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<property name=\"orientation\">1</property>"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"label\">Ethernet</property>"
                      "<property name=\"margin-top\">20</property>"
                      "<property name=\"margin-bottom\">20</property>"
                      "<property name=\"xalign\">0</property>"
                      "<style>"
                      "<class name=\"title-2\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkListBox\" id=\"list_info_con\">"
                      "<child>"
                      "<object class=\"GtkListBoxRow\">"
                      "<property name=\"activatable\">false</property>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"halign\">1</property>"
                      "<property name=\"label\">Direccion IP</property>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_eth\">"
                      "<property name=\"text\">Type here…</property>"
                      "<property name=\"editable\">false</property>"
                      "<property name=\"hexpand\">true</property>"
                      "<property name=\"halign\">2</property>"
                      "<style>"
                      "<class name=\"dim-label\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkListBoxRow\">"
                      "<property name=\"activatable\">false</property>"
                      "<child>"
                      "<object class=\"GtkBox\">"
                      "<child>"
                      "<object class=\"GtkLabel\">"
                      "<property name=\"halign\">1</property>"
                      "<property name=\"label\">Direccion MAC</property>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkEditableLabel\" id=\"ety_info_ip_eth_mac\">"
                      "<property name=\"text\">Type here…</property>"
                      "<property name=\"editable\">false</property>"
                      "<property name=\"hexpand\">true</property>"
                      "<property name=\"halign\">2</property>"
                      "<style>"
                      "<class name=\"dim-label\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "<style>"
                      "<class name=\"rich-list\"/>"
                      "<class name=\"boxed-list\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "<child>"
                      "<object class=\"GtkButton\">"
                      "<property name=\"label\">Configuración</property>"
                      "<property name=\"margin-top\">40</property>"
                      "<property name=\"halign\">3</property>"
                      "<style>"
                      "<class name=\"suggested-action\"/>"
                      "</style>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</child>"
                      "</object>"
                      "</interface>";
  Glib::RefPtr<Gtk::Builder> builder = Gtk::Builder::create();
  Gtk::Box *page_5 = nullptr;

  Gtk::EditableLabel *lbl_red[5] = {nullptr, nullptr, nullptr, nullptr, nullptr};
  sigc::connection poll_info_red;

  void init_datos_red();

public:
  view_six(/* args */);
  ~view_six();
};